### ISSUE TITLE
Getting Dimension ValueError in embedding_input 

### ISSUE THREAD

**Issue by lavanya-m-k** [bhupinderr8/movie_recommendation_LSTM#5]
Hi,  
Thanks for this project, I have created similar dataframe for movie prediction, I also executed the same exact code after creating similar dataframe but I am getting ValueError: Error when checking input: expected embedding_input to have 2 dimensions, but got array with shape (17674, 5, 100)
train_x shape is (17674, 5, 100)
train_y shape is (17674, 100)

Could you please print the shape of train_x and train_y in the notebook you have shared.
Also please let me know If I have missed something

**Comment by lavanya-m-k** [comment]
I tried installing tensorflow 2.2.0 but there is the error still persist but in a different form ValueError: Input 0 of layer lstm is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [None, 5, 100, 200]

**Comment by bhupinderr8** [comment]
Hi there, 
I have changed the model to the train embedding layer in itself instead of using a separate word2vec model. This is why we don't need to pass vectors to the TensorFlow model.
So if you want to use the newer version, you could get rid of the extra dimension. Supposing your sequence length is 5, x_train.shape = (17674, 100)

**Comment by lavanya-m-k** [comment]
Thanks for the response
